// -*- mode: C++; c-file-style: "virtutech-c++" -*-

/*
  © 2024 Intel Corporation

  This software and the related documents are Intel copyrighted materials, and
  your use of them is governed by the express license under which they were
  provided to you ("License"). Unless the License provides otherwise, you may
  not use, modify, copy, publish, distribute, disclose or transmit this software
  or the related documents without Intel's prior written permission.

  This software and the related documents are provided as is, with no express or
  implied warranties, other than those that are expressly stated in the License.
*/

// This file is generated by the script bin/gen-cc-interface

#ifndef CRC32_RTL_DEVICE_CPP_SYSTEMC_CRC32_RTL_INTERFACE_GASKET_H
#define CRC32_RTL_DEVICE_CPP_SYSTEMC_CRC32_RTL_INTERFACE_GASKET_H

#include <simics/systemc/simics2tlm/gasket_owner.h>
#include <simics/systemc/simics2tlm/gasket_adapter.h>


namespace simics {
namespace systemc {
namespace iface {

class Crc32RtlSCInterface {

    // Function convert C interface call to C++ interface call
      public:
        virtual bool start_crc( unsigned int src, unsigned int dst, size_t size, bool blocking) = 0;

        virtual ~Crc32RtlSCInterface() {};
};

}  // namespace iface
}  // namespace systemc
}  // namespace simics

//

namespace simics {
namespace systemc {
namespace simics2tlm {

class Crc32RtlGasketAdapter 
           : public iface::Crc32RtlSCInterface
           , public GasketAdapter<iface::Crc32RtlSCInterface>
{
public:
    Crc32RtlGasketAdapter(iface::Crc32RtlSCInterface *iface, iface::SimulationInterface *simulation)
    : iface_(iface), simulation_(simulation) {}


      public:
        bool start_crc( unsigned int src, unsigned int dst, size_t size, bool blocking)
        {
          Context context(simulation_);
          return iface_->start_crc(src, dst, size, blocking);
        }
        simics2tlm::GasketOwner *gasket_owner() const override
        {
          return dynamic_cast<simics2tlm::GasketOwner *>(iface_);
        }

    private:
        iface::Crc32RtlSCInterface *iface_;
        iface::SimulationInterface *simulation_;
};

class Crc32RtlDevice : public simics::systemc::iface::Crc32RtlSCInterface
                   , public GasketOwner
{
   public:
    Crc32RtlDevice() {
        set_type();
    }
            bool start_crc( unsigned int src, unsigned int dst, size_t size, bool blocking); 

      private:
        iface::TransactionPool pool_;
};

}  // namespace simics2tlm
}  // namespace systemc
}  // namespace simics
#include "crc32_rtl-interface-gasket.cpp"
#endif
